### ISSUE TITLE
Issue with 6 Local Workers

### ISSUE THREAD

**Issue by tlandle** [openmessaging/benchmark#142]
Fails to run with more than 4 local workers. 

17:39:46.988 [main] INFO - Workers list - producers: [http://10.1.1.10:8080, http://0.0.0.0:8080, http://10.1.1.8:8080]
17:39:46.989 [main] INFO - Workers list - consumers: [http://10.1.1.19:8080, http://10.1.1.16:8080, http://10.1.1.17:8080]
17:39:46.996 [main] INFO - --------------- WORKLOAD : 1 producer / 1 consumers on 1 topic --- DRIVER : Pulsar---------------
17:39:47.609 [main] INFO - Created 4 topics in 18.547497 ms
17:39:47.612 [main] ERROR - Failed to run the workload '1 producer / 1 consumers on 1 topic' for driver 'driver-pulsar/pulsar.yaml'
java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
        at java.util.ArrayList$SubList.rangeCheck(ArrayList.java:1225) ~[?:1.8.0_191]
        at java.util.ArrayList$SubList.get(ArrayList.java:1042) ~[?:1.8.0_191]
        at io.openmessaging.benchmark.worker.DistributedWorkersEnsemble.createConsumers(DistributedWorkersEnsemble.java:166) ~[classes/:?]
        at io.openmessaging.benchmark.WorkloadGenerator.createConsumers(WorkloadGenerator.java:289) ~[classes/:?]
        at io.openmessaging.benchmark.WorkloadGenerator.run(WorkloadGenerator.java:76) ~[classes/:?]
        at io.openmessaging.benchmark.Benchmark.lambda$null$0(Benchmark.java:142) ~[classes/:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_191]
        at io.openmessaging.benchmark.Benchmark.lambda$main$1(Benchmark.java:127) ~[classes/:?]
        at java.util.TreeMap.forEach(TreeMap.java:1005) [?:1.8.0_191]
        at io.openmessaging.benchmark.Benchmark.main(Benchmark.java:126) [classes/:?]

**Comment by dave2wave** [comment]
I think that this is fixed.
