### ISSUE TITLE
benchmark-worker HTTP API returning HTTP 500.

### ISSUE THREAD

**Issue by arush15june** [openmessaging/benchmark#168]
```11:51:06.548 [main] INFO - Starting benchmark with config: {
  "drivers" : [ "driver-pulsar/pulsar.yaml" ],
  "workers" : [ "http://benchmark-worker-0.benchmark-worker:8080", "http://benchmark-worker-1.benchmark-worker:8080", "http://benchmark-worker-2.benchmark-worker:8080", "http://benchmark-worker-3.benchmark-worker:8080", "http://benchmark-worker-4.benchmark-worker:8080", "http://benchmark-worker-5.benchmark-worker:8080", "http://benchmark-worker-6.benchmark-worker:8080", "http://benchmark-worker-7.benchmark-worker:8080" ],
  "workersFile" : null,
  "workloads" : [ "workloads/1-topic-16-partitions-1kb.yaml" ]
}
11:51:06.690 [main] INFO - Workloads: {
  "1-topic-16-partitions-1kb" : {
    "name" : "1 producer / 1 consumers on 1 topic",
    "topics" : 1,
    "partitionsPerTopic" : 16,
    "keyDistributor" : "NO_KEY",
    "messageSize" : 1024,
    "payloadFile" : "payload/payload-1Kb.data",
    "subscriptionsPerTopic" : 1,
    "producersPerTopic" : 1,
    "consumerPerSubscription" : 1,
    "producerRate" : 50000,
    "consumerBacklogSizeGB" : 0,
    "testDurationMinutes" : 15
  }
}
11:51:08.303 [main] INFO - Workers list - producers: [http://benchmark-worker-0.benchmark-worker:8080, http://benchmark-worker-1.benchmark-worker:8080, http://benchmark-worker-2.benchmark-worker:8080, http://benchmark-worker-3.benchmark-worker:8080]
11:51:08.305 [main] INFO - Workers list - consumers: [http://benchmark-worker-4.benchmark-worker:8080, http://benchmark-worker-5.benchmark-worker:8080, http://benchmark-worker-6.benchmark-worker:8080, http://benchmark-worker-7.benchmark-worker:8080]
11:51:08.345 [main] INFO - --------------- WORKLOAD : 1 producer / 1 consumers on 1 topic --- DRIVER : Pulsar---------------
11:51:09.491 [AsyncHttpClient-2-1] ERROR - Failed to do HTTP post request to http://benchmark-worker-0.benchmark-worker:8080/stop-all -- code: 500
11:51:09.494 [AsyncHttpClient-2-2] ERROR - Failed to do HTTP post request to http://benchmark-worker-3.benchmark-worker:8080/stop-all -- code: 500
11:51:09.506 [AsyncHttpClient-2-2] ERROR - Failed to do HTTP post request to http://benchmark-worker-5.benchmark-worker:8080/stop-all -- code: 500
11:51:09.509 [AsyncHttpClient-2-2] ERROR - Failed to do HTTP post request to http://benchmark-worker-1.benchmark-worker:8080/stop-all -- code: 500
11:51:09.510 [AsyncHttpClient-2-1] ERROR - Failed to do HTTP post request to http://benchmark-worker-2.benchmark-worker:8080/stop-all -- code: 500
11:51:09.520 [AsyncHttpClient-2-1] ERROR - Failed to do HTTP post request to http://benchmark-worker-6.benchmark-worker:8080/stop-all -- code: 500
11:51:09.573 [AsyncHttpClient-2-1] ERROR - Failed to do HTTP post request to http://benchmark-worker-4.benchmark-worker:8080/stop-all -- code: 500
11:51:09.577 [main] ERROR - Failed to run the workload '1 producer / 1 consumers on 1 topic' for driver 'driver-pulsar/pulsar.yaml'
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_171]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_171]
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604) ~[?:1.8.0_171]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_171]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_171]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[?:1.8.0_171]
        at org.asynchttpclient.netty.NettyResponseFuture.getContent(NettyResponseFuture.java:226) ~[org.asynchttpclient-async-http-client-2.1.0-alpha26.jar:?]
        at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:261) ~[org.asynchttpclient-async-http-client-2.1.0-alpha26.jar:?]
        at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.finishUpdate(AsyncHttpClientHandler.java:239) ~[org.asynchttpclient-async-http-client-2.1.0-alpha26.jar:?]
        at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:120) ~[org.asynchttpclient-async-http-client-2.1.0-alpha26.jar:?]
        at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:149) ~[org.asynchttpclient-async-http-client-2.1.0-alpha26.jar:?]
        at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:76) ~[org.asynchttpclient-async-http-client-2.1.0-alpha26.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) ~[io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_171]
Caused by: java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:121) ~[com.google.guava-guava-23.3-jre.jar:?]
        at io.openmessaging.benchmark.worker.DistributedWorkersEnsemble.lambda$sendPost$6(DistributedWorkersEnsemble.java:268) ~[io.openmessaging.benchmark-benchmark-framework-0.0.1-SNAPSHOT.jar:?]
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_171]
        ... 39 more
```

All benchmark workers are running in a digitalocean kubernetes cluster with 3 nodes. When I try to run the the benchmark using the command in `deployment/kubernetes/helm/README.md` it fails with the above error. All the benchmark-workers are returning HTTP 500 status codes.

**Comment by enrico9034** [comment]
same errors, how you resolve it?

**Comment by AarushAhuja** [comment]
I wasn't able to resolve it. Instead, decided to try out the terraform scripts and even they didnt work.
Ended up not being able to run the benchmark at all!

**Comment by AarushAhuja** [comment]
I wasn't able to resolve it. Instead, decided to try out the terraform scripts and even they didnt work.
Ended up not being able to run the benchmark at all!

**Comment by arush15june** [comment]
I wasn't able to resolve it. Instead, decided to try out the terraform scripts and even they didnt work.
Ended up not being able to run the benchmark at all!

**Comment by yabinmeng** [comment]
Ran into a similar issue, HTTP 500 error returns when creating consumers (http://<IP>:8080/create-consumers)

`
21:14:58.237 [main] INFO - Workers list - producers: [http://<IP1>:8080]
21:14:58.237 [main] INFO - Workers list - consumers: [http://<IP2>:8080]
21:14:58.240 [main] INFO - --------------- WORKLOAD : Simple Workload 1 producer on 1 topic --- DRIVER : Pulsar---------------
21:14:58.573 [main] INFO - Created 1 topics in 40.125393 ms
21:14:58.662 [AsyncHttpClient-3-2] ERROR - Failed to do HTTP post request to http://<IP>:8080/create-consumers -- code: 500
21:14:58.663 [main] ERROR - Failed to run the workload 'Simple Workload 1 producer on 1 topic' for driver 'driver-pulsar/pulsar.yaml'
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_272]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_272]
	at java.util.concurrent.
`

**Comment by dave2wave** [comment]
Did you update the real IP addresses with `<IP>` for this issue?

**Comment by luk-sam** [comment]
any updates regarding this issue?
