### ISSUE TITLE
Exception in thread "main" java.util.concurrent.CompletionException: java.net.ConnectException: Connection refused: /10.0.0.*:8080

### ISSUE THREAD

**Issue by rahulpandeycs** [openmessaging/benchmark#189]
```
[ec2-user@ip-10-0-0-*benchmark]sudo bin/benchmark --drivers driver-kafka/kafka.yaml workloads/1-topic-16-partitions-1kb.yaml
18:21:23.398 [main] INFO - Using default worker file workers.yaml
18:21:23.402 [main] INFO - Reading workers list from workers.yaml
18:21:23.445 [main] INFO - Starting benchmark with config: {
  "drivers" : [ "driver-kafka/kafka.yaml" ],
  "workers" : [ "http://10.0.0.*:8080", "http://10.0.0.*:8080", "http://10.0.0.*:8080", "http://10.0.0.*:8080" ],
  "workersFile" : "/opt/benchmark/workers.yaml",
  "workloads" : [ "workloads/1-topic-16-partitions-1kb.yaml" ]
}
18:21:23.458 [main] INFO - Workloads: {
  "1-topic-16-partitions-1kb" : {
    "name" : "1 producer / 1 consumers on 1 topic",
    "topics" : 1,
    "partitionsPerTopic" : 16,
    "keyDistributor" : "NO_KEY",
    "messageSize" : 1024,
    "useRandomizedPayloads" : false,
    "randomBytesRatio" : 0.0,
    "randomizedPayloadPoolSize" : 0,
    "payloadFile" : "payload/payload-1Kb.data",
    "subscriptionsPerTopic" : 1,
    "producersPerTopic" : 1,
    "consumerPerSubscription" : 1,
    "producerRate" : 50000,
    "consumerBacklogSizeGB" : 0,
    "testDurationMinutes" : 15
  }
}
18:21:23.696 [main] INFO - Workers list - producers: [http://10.0.0.*:8080, http://10.0.0.*:8080]
18:21:23.697 [main] INFO - Workers list - consumers: [http://10.0.0.*:8080, http://10.0.0.*:8080]
18:21:23.700 [main] INFO - --------------- WORKLOAD : 1 producer / 1 consumers on 1 topic --- DRIVER : Kafka---------------
18:21:23.785 [main] ERROR - Failed to run the workload '1 producer / 1 consumers on 1 topic' for driver 'driver-kafka/kafka.yaml'
java.util.concurrent.CompletionException: java.net.ConnectException: Connection refused: /10.0.0.*:8080
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_292]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_292]
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:607) ~[?:1.8.0_292]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591) ~[?:1.8.0_292]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_292]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) ~[?:1.8.0_292]
```

**Comment by dave2wave** [comment]
`http://10.0.0.*:8080` is not a valid url. Please configure your driver files with valid local ip addresses for your worker files. Ansible playbooks do this like so:

deploy.yaml
```
    - template:
        src: "templates/workers.yaml"
        dest: "/opt/benchmark/workers.yaml"
```

templates/workers.yaml
```
workers:
{% for worker in groups['client'] %}
  - http://{{ hostvars[worker].private_ip }}:8080
{% endfor %}
```
