### ISSUE TITLE
NoClassDefFoundError exception starting benchmark-worker

### ISSUE THREAD

**Issue by ankorus** [openmessaging/benchmark#223]
13:39:38.234 [main] INFO - Javalin has started \o/
Exception in thread "main" java.lang.NoClassDefFoundError: io/openmessaging/benchmark/driver/ConsumerCallback
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at io.openmessaging.benchmark.worker.WorkerHandler.<init>(WorkerHandler.java:48)
        at io.openmessaging.benchmark.worker.BenchmarkWorker.main(BenchmarkWorker.java:89)

**Comment by ankorus** [comment]
mvn --version
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /usr/local/apache-maven/apache-maven-3.8.4
Java version: 1.8.0_272, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.272.b10-1.el7_9.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1160.6.1.el7.x86_64", arch: "amd64", family: "unix"
