### ISSUE TITLE
Worker process can hang when it fails to start

### ISSUE THREAD

**Issue by travisdowns** [openmessaging/benchmark#292]
Sometimes, the worker process will hang when it fails to start. This may give the erroneous impression that the worker is ready when it is not.

One example of this occurs when the following exception is thrown when the Prometheus port is already in use:

```
Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Failed to bind to /0.0.0.0:9091
   at org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider.start(PrometheusMetricsProvider.java:114)
   at io.openmessaging.benchmark.worker.BenchmarkWorker.main(BenchmarkWorker.java:72)
Caused by: java.io.IOException: Failed to bind to /0.0.0.0:9091
   at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349)
   at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310)
   at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
   at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
   at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
   at org.eclipse.jetty.server.Server.doStart(Server.java:401)
   at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
   at org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider.start(PrometheusMetricsProvider.java:111)
   ... 1 more
Caused by: java.net.BindException: Address already in use
   at java.base/sun.nio.ch.Net.bind0(Native Method)
   at java.base/sun.nio.ch.Net.bind(Net.java:459)
   at java.base/sun.nio.ch.Net.bind(Net.java:448)
   at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
   at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
   at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344)
   ... 8 more
```

After this exception the worker remains running with non-daemon Jetty threads still active.

The specific bug here appears to be in `PrometheusMetricsProvider.start` which does not clean up correctly when an exception is thrown (leaving jetty running), but this is just an example and we can fix this in one shot by using the pattern already used in this code: catching exceptions and calling `System.exit` to terminate the worker explicitly.

**Comment by travisdowns** [comment]
Not stale.

**Comment by travisdowns** [comment]
Not stale.
