### ISSUE TITLE
[Bug] Local Test fails with Netty NoClassDefFoundError

### ISSUE THREAD

**Issue by heesung-sn** [openmessaging/benchmark#363]
Issue:
The driver fails to find Netty classes, which blocks benchmark test development on local env.

Replication Steps:

- build: mvn clean install -DskipTests 
- Start Worker1: bin/benchmark-worker --port 9090 --stats-port 9091
- Start Worker2: bin/benchmark-worker --port 9092 --stats-port 9093
- Start Driver: bin/benchmark --drivers driver-pulsar/pulsar.yaml --workers http://localhost:9090,http://localhost:9092 workloads/1-topic-16-partitions-1kb.yaml

Driver Failure Logs:
```
09:52:49.903 [main] INFO DistributedWorkersEnsemble - Workers list - producers: [http://localhost:9090]
09:52:49.906 [main] INFO DistributedWorkersEnsemble - Workers list - consumers: http://localhost:9092
09:52:49.921 [main] INFO Benchmark - --------------- WORKLOAD : 1 producer / 1 consumers on 1 topic --- DRIVER : Pulsar---------------
09:52:55.144 [AsyncHttpClient-5-1] WARN ChannelInitializer - Failed to initialize a channel. Closing: [id: 0x6a5276a4]
java.lang.NoClassDefFoundError: Could not initialize class io.netty.handler.codec.http.HttpClientCodec$Encoder
	at io.netty.handler.codec.http.HttpClientCodec.<init>(HttpClientCodec.java:139) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.http.HttpClientCodec.<init>(HttpClientCodec.java:128) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.http.HttpClientCodec.<init>(HttpClientCodec.java:118) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at org.asynchttpclient.netty.channel.ChannelManager.newHttpClientCodec(ChannelManager.java:332) ~[async-http-client-2.12.3.jar:?]
	at org.asynchttpclient.netty.channel.ChannelManager.access$100(ChannelManager.java:70) ~[async-http-client-2.12.3.jar:?]
	at org.asynchttpclient.netty.channel.ChannelManager$1.initChannel(ChannelManager.java:221) ~[async-http-client-2.12.3.jar:?]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]
09:52:55.144 [AsyncHttpClient-3-1] WARN ChannelInitializer - Failed to initialize a channel. Closing: [id: 0x07a744f5]
java.lang.NoSuchMethodError: io.netty.util.internal.ReferenceCountUpdater.setInitialValue(Lio/netty/util/ReferenceCounted;)V
	at io.netty.buffer.AbstractReferenceCountedByteBuf.<init>(AbstractReferenceCountedByteBuf.java:50) ~[netty-buffer-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.buffer.UnpooledDirectByteBuf.<init>(UnpooledDirectByteBuf.java:54) ~[netty-buffer-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.<init>(UnpooledUnsafeDirectByteBuf.java:41) ~[netty-buffer-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.buffer.UnpooledUnsafeNoCleanerDirectByteBuf.<init>(UnpooledUnsafeNoCleanerDirectByteBuf.java:25) ~[netty-buffer-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeNoCleanerDirectByteBuf.<init>(UnpooledByteBufAllocator.java:181) ~[netty-buffer-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.buffer.UnpooledByteBufAllocator.newDirectBuffer(UnpooledByteBufAllocator.java:91) ~[netty-buffer-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188) ~[netty-buffer-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179) ~[netty-buffer-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.buffer.Unpooled.directBuffer(Unpooled.java:128) ~[netty-buffer-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.http.HttpObjectEncoder.<clinit>(HttpObjectEncoder.java:53) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.http.HttpClientCodec.<init>(HttpClientCodec.java:139) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.http.HttpClientCodec.<init>(HttpClientCodec.java:128) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.http.HttpClientCodec.<init>(HttpClientCodec.java:118) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at org.asynchttpclient.netty.channel.ChannelManager.newHttpClientCodec(ChannelManager.java:332) ~[async-http-client-2.12.3.jar:?]
	at org.asynchttpclient.netty.channel.ChannelManager.access$100(ChannelManager.java:70) ~[async-http-client-2.12.3.jar:?]
	at org.asynchttpclient.netty.channel.ChannelManager$1.initChannel(ChannelManager.java:221) ~[async-http-client-2.12.3.jar:?]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.65.Final.jar:4.1.65.Final]
```

**Comment by richardartoul** [comment]
@heesung-sn did you figure this out? I'm struggling with same thing and am not really a java expert

**Comment by heesung-sn** [comment]
I think we can workaround this error by an earlier client version like 2.9.2.

**Comment by skykistler** [comment]
I was able to resolve this with this change - 
https://github.com/openmessaging/benchmark/pull/376

**Comment by heesung-sn** [comment]
@skykistler thank you for the fix
