### ISSUE TITLE
Benchmark failed with ArrayIndexOutOfBoundException.

### ISSUE THREAD

**Issue by amit-kumar59** [openmessaging/benchmark#369]
I am running perf test for Pravega and the log is full with ArrayIndexOutOfBoundException .

We are using Histogram version **org.hdrhistogram-HdrHistogram-2.1.12.jar:2.1.12**
The log message is 

`05:19:59.547 [main] INFO - Pub rate  2445.5 msg/s / 233.2 MB/s | Cons rate     0.0 msg/s /  0.0 MB/s | Backlog:  0.0 K | Pub Latency (ms) avg: 1064.4 - 50%: 23.1 - 99%: 14405.3 - 99.9%: 18498.4 - Max: 18773.0
05:20:08.789 [clientInternal-3-8] WARN - Write error on message
java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException: value 67642727 outside of histogram covered range. Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1311762 out of bounds for length 1310720
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl$ResponseProcessor.lambda$ackUpTo$5(SegmentOutputStreamImpl.java:455) ~[io.pravega-pravega-client-0.13.0-3164.43a7e9d-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at io.pravega.common.concurrent.ThreadPoolScheduledExecutorService$ScheduledRunnable.run(ThreadPoolScheduledExecutorService.java:193) [io.pravega-pravega-common-0.13.0-3164.43a7e9d-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: value 67642727 outside of histogram covered range. Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1311762 out of bounds for length 1310720
	at org.HdrHistogram.AbstractHistogram.handleRecordException(AbstractHistogram.java:571) ~[org.hdrhistogram-HdrHistogram-2.1.12.jar:2.1.12]
	at org.HdrHistogram.AbstractHistogram.recordSingleValue(AbstractHistogram.java:563) ~[org.hdrhistogram-HdrHistogram-2.1.12.jar:2.1.12]
	at org.HdrHistogram.AbstractHistogram.recordValue(AbstractHistogram.java:467) ~[org.hdrhistogram-HdrHistogram-2.1.12.jar:2.1.12]
	at org.HdrHistogram.Recorder.recordValue(Recorder.java:136) ~[org.hdrhistogram-HdrHistogram-2.1.12.jar:2.1.12]
	at io.openmessaging.benchmark.worker.LocalWorker.lambda$submitProducersToExecutor$8(LocalWorker.java:229) ~[io.openmessaging.benchmark-benchmark-framework-0.0.1-SNAPSHOT.jar:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783) ~[?:?]
	... 8 mor`

**Comment by travisdowns** [comment]
Not stale.
